window.LESSONS = [
["My dog knows exactly when I open a bag of snacks.","うちの犬は、私がお菓子の袋を開けるとすぐに気づきます。"],
["I waved back at a stranger who wasn’t waving at me.","知らない人に手を振り返したら、私に振っていたんじゃなかった。"],
["I made coffee and forgot to drink it until lunchtime.","コーヒーを入れたのに、お昼まで飲むのを忘れていました。"],
["My cat has three beds but still sleeps on my chair.","うちの猫にはベッドが3つあるのに、いつも私の椅子で寝ます。"],
["I opened the fridge and forgot what I was looking for.","冷蔵庫を開けて、何を探していたのか忘れました。"],
["The little boy thanked the bus driver before getting off.","小さな男の子は、降りる前にバスの運転手さんに「ありがとう」と言いました。"],
["My neighbor leaves fresh flowers outside for anyone to take.","近所の人が、誰でも持っていけるように外にお花を置いています。"],
["I found a note in my lunch that said, “Have a good day!”","お弁当の中に「よい一日を！」と書かれたメモが入っていました。"],
["An old man smiled at me and said, “Beautiful day, isn’t it?”","おじいさんが私に笑いかけて、「いい天気だね」と言いました。"],
["The baby stopped crying when the dog sat beside her.","犬がそばに座ると、赤ちゃんは泣きやみました。"],
["I missed my train, but I found a great little café nearby.","電車に乗り遅れたけれど、近くに素敵な小さなカフェを見つけました。"],
["I bought a cake for my friend and ate one piece on the way.","友達にケーキを買ったのに、途中で一切れ食べてしまいました。"],
["My father still calls me when he sees something funny on TV.","父はいまでもテレビで面白いものを見ると、私に電話してきます。"],
["Someone left a tiny umbrella over the flowers in the garden.","誰かが庭の花に小さな傘をさしていました。"],
["I spent ten minutes looking for my glasses. They were on my head.","10分もメガネを探しました。頭の上にありました。"],
["The dog brought me his favorite toy when I came home tired.","疲れて帰宅したら、犬がお気に入りのおもちゃを持ってきてくれました。"],
["I took the wrong bus and discovered a part of town I’d never seen.","バスを間違えて、見たことのない街の一角を知りました。"],
["My grandmother sends me birthday cards two weeks early every year.","祖母は毎年、誕生日カードを2週間も早く送ってきます。"],
["I put my phone in a safe place and couldn’t find it later.","スマホを安全な場所にしまったら、あとで見つけられなくなりました。"],
["My dog waits by the window five minutes before I usually come home.","うちの犬は、私がいつも帰る5分前から窓辺で待っています。"],
["I ordered a small coffee, but they gave me the biggest one.","小さいコーヒーを頼んだのに、一番大きいものが出てきました。"],
["A little girl held the door open for me at the store.","小さな女の子がお店のドアを開けて待っていてくれました。"],
["I checked the weather three times and still forgot my umbrella.","天気予報を3回も確認したのに、傘を忘れました。"],
["My mother keeps every birthday card I’ve ever given her.","母は、私が今まで贈った誕生日カードを全部とってあります。"],
["I went upstairs to get something and forgot why I was there.","何かを取りに2階へ行ったのに、何をしに来たのか忘れました。"],
["The waiter remembered my usual order before I said anything.","何も言わないうちに、店員さんがいつもの注文を覚えていてくれました。"],
["My dog heard the word “walk” from the other side of the house.","うちの犬は、家の反対側にいたのに「散歩」という言葉を聞きつけました。"],
["I found some money in a coat I hadn’t worn since last winter.","去年の冬から着ていなかったコートの中からお金が出てきました。"],
["A stranger returned the wallet I dropped on the train.","電車で落とした財布を、知らない人が届けてくれました。"],
["I woke up early on Saturday because I thought it was Monday.","月曜日だと思って、土曜日なのに早起きしてしまいました。"],
["My friend said she wasn’t hungry and then ate half my fries.","友達はお腹が空いていないと言ったのに、私のポテトを半分食べました。"],
["The rain stopped just as we were about to leave the house.","家を出ようとしたちょうどそのとき、雨がやみました。"],
["My grandfather tells the same joke every Christmas, and we still laugh.","祖父は毎年クリスマスに同じ冗談を言いますが、私たちは今でも笑います。"],
["I bought a plant last year, and somehow it’s still alive.","去年植物を買ったのですが、どういうわけかまだ元気です。"],
["The cat ignored me all day and then slept beside me at night.","猫は一日中私を無視していたのに、夜になると隣で寝ました。"],
["I found my missing sock inside the sleeve of my sweater.","なくした靴下がセーターの袖の中から出てきました。"],
["The woman in front of me paid for my coffee by mistake.","前にいた女性が間違えて私のコーヒーまで払ってくれました。"],
["My nephew thinks I can fix anything because I own a screwdriver.","甥っ子は、私がドライバーを持っているので何でも直せると思っています。"],
["I tried to take a photo of the moon, but it looked like a potato.","月の写真を撮ろうとしたら、ジャガイモみたいに写りました。"],
["My dog stole my seat the moment I stood up.","立ち上がった瞬間、犬に席を取られました。"],
["I smiled at a baby on the train, and she smiled back.","電車で赤ちゃんに笑いかけたら、笑い返してくれました。"],
["I finally cleaned my desk and found the pen I bought yesterday.","やっと机を片づけたら、昨日買ったペンが見つかりました。"],
["My sister called just to tell me she saw a beautiful rainbow.","姉はきれいな虹を見たことを伝えるためだけに電話してきました。"],
["I tried to whisper, but everyone in the room heard me.","小声で話したつもりなのに、部屋にいた全員に聞こえていました。"],
["The bakery gave me an extra cookie because one was slightly broken.","クッキーが少し割れていたので、パン屋さんがおまけを一枚くれました。"],
["My dog looks surprised every morning when I give him breakfast.","うちの犬は毎朝ごはんをあげるたびに驚いた顔をします。"],
["I found an old photo and remembered exactly where we took it.","古い写真を見つけて、どこで撮ったのかすぐに思い出しました。"],
["I wore two different socks all day and nobody noticed.","一日中左右違う靴下を履いていましたが、誰も気づきませんでした。"],
["The little girl next door drew a picture of my dog for me.","隣の家の女の子が、うちの犬の絵を描いてくれました。"],
["I bought a new notebook because the old one was too nice to use.","古いノートがもったいなくて使えないので、新しいノートを買いました。"]
];
